<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="DisplayProducts.aspx.cs" Inherits="InventoryClient.DisplayProducts" %>



<asp:Content ID="BodyContent" ContentPlaceHolderID="MainContent" runat="server">
    <link href="StyleSheet1.css"  rel="stylesheet" type="text/css" />
    <div class="MyFont Centralize">
        
        <br />
        <br />
        CURRENT DATABASE
        <br />
        <br />
        </div>
        <div>
        &nbsp;<asp:Button ID="Button1" runat="server"  Height="42px" class="MyFont Centralize button button2 padder"  Text="Refresh" Width="203px" OnClick="Button1_Click" />
            <asp:TextBox ID="TextBox1" runat="server" CssClass="rightside pos" Width="117px" Height="23px"></asp:TextBox>
            <asp:Button ID="Button2" runat="server" Text="Search" CssClass="MyFont button button2 pos" OnClick="Button2_Click" />
            <asp:Label ID="Label2" runat="server" Text="Name:" CssClass="Centralize"></asp:Label>
        </div>
        <br />
        <asp:GridView ID="GridView1" runat="server" CssClass="MyFont GridViewTable" HeaderStyle-BackColor="#3AC0F2"
        HeaderStyle-ForeColor="White" RowStyle-BackColor="#A1DCF2" AlternatingRowStyle-BackColor="White"
        RowStyle-ForeColor="#3A3A3A" RowStyle-HorizontalAlign="Center" AutoGenerateEditButton="True" OnRowUpdating="GridView1_RowUpdating" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" AutoGenerateDeleteButton="True" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdated="GridView1_RowUpdated" Width="714px">
<AlternatingRowStyle BackColor="White"></AlternatingRowStyle>

<HeaderStyle BackColor="#3AC0F2" ForeColor="White"></HeaderStyle>

<RowStyle HorizontalAlign="Center" BackColor="#A1DCF2" ForeColor="#3A3A3A"></RowStyle>
        </asp:GridView>
        <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label>
        <br />
        <asp:RadioButtonList ID="RadioButtonList1" runat="server" AutoPostBack="True" RepeatDirection="Horizontal"  OnSelectedIndexChanged="RadioButtonList1_SelectedIndexChanged" CellPadding="5" CellSpacing="5" CssClass="list" BorderStyle="None" BorderWidth="0px">
        </asp:RadioButtonList>
    

    </asp:Content>